[package]
name = "minecraft-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
dirs = "4.0.0"
futures = "0.3.17"
serde_json = "1.0.72"

[dependencies.reqwest]
version = "0.11.5"
features = ["stream"]

[dependencies.tokio]
version = "1.14.0"
features = ["full"]
