[package]
name = "minecraft-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.5"
futures = "0.3.18"
serde_json = "1.0.72"

[dependencies.tokio]
version = "1.14.0"
features = ["full"]